services:
  postgres:
    image: postgres:latest
    container_name: pandora_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
